### ISSUE TITLE
places are broken Please fix

### ISSUE THREAD

**Issue by James567894** [CloneTrooper1019/Roblox-Client-Watch#11]
All these places and i kept getting "The file header is corrupted"

When I open the place and then I got an error that say "The file header is corrupted"

Either these place are outdate version of ROBLOX Studio

https://github.com/CloneTrooper1019/Roblox-Client-Watch/tree/master/places

**Comment by James567894** [comment]
@CloneTrooper1019 Still waiting.

**Comment by CloneTrooper1019** [comment]
I'll look into it.
