### ISSUE TITLE
Make rbxPkgManifest.txt & rbxManifest.txt readable

### ISSUE THREAD

**Issue by mkargus** [CloneTrooper1019/Roblox-Client-Watch#14]
<b>Problem:</b> The current layout for both files is just awful even with using the ReadMe as a reference. It's a general mess that needs to be cleaned up.
<br>

<b>Solution / Idea:</b> Convert these two files into a CSV (comma-separated values) as Github has [a built-in viewer](https://blog.github.com/2013-08-22-see-your-csvs) that can make these files more readable. _For some reason, it doesn't work on mobile_

<details>
 <summary>Example: rbxPkgManifest | Before & After</summary>
<p>Before | https://github.com/CloneTrooper1019/Roblox-Client-Watch/blob/6c838697bc9320cdc4282574aa9780a34e99cd0c/rbxPkgManifest.txt</p>
<img src="https://user-images.githubusercontent.com/14226603/48353904-78a20b00-e65e-11e8-99f2-093c6671a303.png">
<br>
<p>After | https://gist.github.com/mkargus/696adffeb1128f227f2b528881888fc3</p>
<img src="https://user-images.githubusercontent.com/14226603/48354012-b0a94e00-e65e-11e8-8608-b383e473227d.png">
</details>

<details>
 <summary>Example: rbxManifest | Before & After</summary>
<p>Before | https://github.com/CloneTrooper1019/Roblox-Client-Watch/blob/6c838697bc9320cdc4282574aa9780a34e99cd0c/rbxManifest.txt</p>
<img src="https://user-images.githubusercontent.com/14226603/48354431-ba7f8100-e65f-11e8-8632-6263feb87449.png">
<br>
<p>After | https://gist.github.com/mkargus/8210255de8ed82d4cd3c6bb101ff3a98</p>
<img src="https://user-images.githubusercontent.com/14226603/48354458-ce2ae780-e65f-11e8-9576-f25badfd4118.png">
</details>

**Comment by MaximumADHD** [comment]
Great idea! I’ll see what I can do.

**Comment by MaximumADHD** [comment]
Alright, its in.

https://github.com/CloneTrooper1019/Roblox-Client-Watch/blob/roblox/rbxManifest.csv
https://github.com/CloneTrooper1019/Roblox-Client-Watch/blob/roblox/rbxPkgManifest.csv
