### ISSUE TITLE
rbxManifest.csv too large to be displayed as CSV

### ISSUE THREAD

**Issue by Kan18** [CloneTrooper1019/Roblox-Client-Watch#19]
When attempting to view rbxManifest.csv in the browser, this happens:
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/24967425/87796649-a23e0d00-c817-11ea-8e5d-752453299f14.png">
According to [GitHub's documentation](https://docs.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data#handling-errors), the file is 2 KB too large to be displayed in the browser.
This makes the .csv almost entirely useless, except for exporting data.

**Comment by MaximumADHD** [comment]
Heh, well this wasn’t the case a few years ago but Roblox has continued to pile lots of new Lua files into their manifest. Since this issue is on GitHub’s end there isn’t much I can do.

The file is at least slightly more readable than rbxManifest.txt :)!

**Comment by MaximumADHD** [comment]
Viewing it raw seems to work fine now, so I’ll be closing this.
