### ISSUE TITLE
Object Insert

### ISSUE THREAD

**Issue by SnowyShiro** [CloneTrooper1019/Roblox-Client-Watch#23]
Is there any way to get what instances are in the object insert?
The reflection manifest tells you them all, but it also has some more in them than what shows in rbx studio.

**Comment by MaximumADHD** [comment]
Use [API-Dump.json](https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/API-Dump.json) :)!

**Comment by SnowyShiro** [comment]
?

**Comment by MaximumADHD** [comment]
I'm not 100% sure of the exact logic they use to determine this, but categorization is determined through [ReflectionMetadata.xml](https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/ReflectionMetadata.xml) as you mentioned, and there's a file called [StudioFavorites.json](https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/QtResources/Features/DataModelEditing/InsertObject/settings/StudioFavorites.json) embedded in the QtResources which determines what objects show up in the "Frequently Used" category of a given selected object.

Whether an object can be inserted can also be inferred by its tags in the [JSON API Dump](https://github.com/MaximumADHD/Roblox-Client-Tracker/blob/roblox/API-Dump.json). Tags such as `NotCreatable`, `NotBrowsable`, and `Deprecated` are good indicators that an object won't typically appear in the object insertion window.
