### ISSUE TITLE
Output .luac files in a readable disassembly

### ISSUE THREAD

**Issue by ghost** [CloneTrooper1019/Roblox-Client-Watch#28]
Roblox-Client-Tracker has started dumping the compiled sourcecode for bytecode plugins (thanks)

However, `.luac` in its current format makes it a little hard to figure out what the plugin is doing. I would instead like it if a disassembled version of the bytecode was also left besides the `.luac` document, maybe `.luac.disassembly`?

(for example, here's a basic `HelloWorld.luac` alongside it's disassembly file
```
03 02 05 70 72 69 6E 74 0C 48 65 6C 6C 6F 20 57
6F 72 6C 64 21 01 02 00 00 01 06 41 00 00 00 0C
00 01 00 00 00 00 40 05 01 02 00 15 00 02 01 16
00 01 00 03 03 01 04 00 00 00 40 03 02 00 01 00
00 00 00
```

And here's what this could like in disassembly form

```
; PROTO_0(...)

PREPVARARGS
GETIMPORT  R0 = K1  ; K1 = print
LOADK      R1 = K2  ; K2 = "Hello World!"
CALL       R0(R1)   ; print("Hello World")
RETURN
```

Myself does not know how to use most of the info to process debugs or actually decompile the script, but for the time being, this format is probably enough

**Comment by MaximumADHD** [comment]
I’m actually hoping to decompile them completely. I was looking into luauDec but it’s currently out of date and I was having trouble getting it to work properly with the newer versions of Luau.

**Comment by ghost** [comment]
I have a very high suspicion of whats actually happening here. From version 2 onwards in the bytecode spec, it added a new byte in every proto called `LINEDEFINED`, this was a fix for an issue with debug.info. Version 3 just added new operations around for loops and if-then-else statements

**Comment by metatablecat** [comment]
![image](https://github.com/MaximumADHD/Roblox-Client-Tracker/assets/132796135/7c54d5ce-3b9d-485f-91ad-45172a7d6cce)
oh yeah also something isn't dumping the bytecode correctly (i have a new account now)

**Comment by ryanlua** [comment]
Any updates on this issue? I would **love** to see the source of the plugins from Roblox to learn from them since they know best (mostly, except to putting their plugins in luac in the first place).

**Comment by MaximumADHD** [comment]
So I’ve been poking at this again lately. The reason it was writing the data wrong was because of a sanitization pass I was putting all strings written through. Even with this fix Luau is still getting bad data and I’m struggling to figure out why. It’s running through the original C++ code, but I’m still seeing random bad data.

**Comment by metatablecat** [comment]
Could I have one of these exports to see if I could figure out what in the bad data is causing the issue, previously it was Windows thinking the data was plaintext and converting some binary data. (such as newline chars), though I feel like thats not the issue anymore.

**Comment by karl-police** [comment]
Where do those ``.luac`` files come from???????
