### ISSUE TITLE
addition of playstation data?

### ISSUE THREAD

**Issue by xNasuni** [CloneTrooper1019/Roblox-Client-Watch#29]
i'm pretty sure that in Q4 2023 roblox for playstation was released, and just like there is xbox data here, shouldn't there also be playstation data too?

**Comment by bluepilledgreat** [comment]
Only studio data is dumped

**Comment by MaximumADHD** [comment]
Yeah, I don’t know what additional data I could get from the PlayStation version.

**Comment by xNasuni** [comment]
idk, just thought that since xbox was on there maybe play station would be on there aswell but i guess it doesn't matter
