### ISSUE TITLE
A new way to find zcanary and zintegration channel versions

### ISSUE THREAD

**Issue by brandonilester** [CloneTrooper1019/Roblox-Client-Watch#30]
Hi, I've seen the devfourm of you saying to bring back zcanary and zintegration versions. I did find a way to get them.
http://setup.rbxcdn.com/channel/zcanary/version
http://setup.rbxcdn.com/channel/zintegration/version
Hope this helps a bit.

**Comment by MaximumADHD** [comment]
Those are for 32-bit client builds and they aren't updated anymore.
