### ISSUE TITLE
Half of valid fast variables are gone from FVariables.txt

### ISSUE THREAD

**Issue by Lachine1** [CloneTrooper1019/Roblox-Client-Watch#34]
🙏

**Comment by MaximumADHD** [comment]
What, the Lua ones?

**Comment by robuxlarp** [comment]
> What, the Lua ones?

Not just Lua ones, but cpp ones too. A lot of cpp ones got deleted and some got duplicated.
This happened in https://github.com/MaximumADHD/Roblox-Client-Tracker/commit/6d02137ad5be81d1cda4dc71d7c25f6cf3879866

I also looked through Roblox in a hex editor and some flags don't match up

**Comment by Lachine1** [comment]
> What, the Lua ones?

Even FFlagDebugDisplayFPS is gone

**Comment by Lachine1** [comment]
nvm its updated skibidi
